### ISSUE TITLE
Failed when running on EC2

### ISSUE THREAD

**Issue by keith-turner** [fluo-io/webindex#34]
I tried running `webindex copy` on EC2 and saw the following failure.   I suspect the remote task is trying to access the paths which is on the machine that started the job but not on any of the workers.

```
Caused by: java.io.FileNotFoundException: File file:/home/ec2-user/webindex/paths/2015-18.wat.paths does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:534)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:747)

```

**Comment by keith-turner** [comment]
fixed by #35
